set clipboard=unnamed
syntax on
set number
set mouse=a
set t_Co=256
set encoding=utf-8
set tabstop=4
set shiftwidth=4
set softtabstop=4
set autoindent
set expandtab
set nowrap
set exrc

" Ex sudo in vim
cmap w!! w !sudo tee > /dev/null %

" Ask to make directory if does not exist
augroup vimrc-auto-mkdir
    autocmd!
    autocmd BufWritePre * call s:auto_mkdir(expand('<afile>:p:h'), v:cmdbang)
    function! s:auto_mkdir(dir, force)
        if !isdirectory(a:dir)
            \ && (a:force
            \ || input("'" . a:dir . "' does not exist. Create? [y/N]") =~? '^y\%[es]$')
            call mkdir(iconv(a:dir, &encoding, &termencoding), 'p')
        endif
    endfunction
augroup END

call plug#begin()
Plug 'preservim/nerdtree'
Plug 'vim-scripts/indentpython.vim'
Plug 'valloric/YouCompleteMe'
call plug#end()

" NERDTree configurations
map <C-n> :NERDTreeToggle<CR> | let NERDTreeWinSize = 15 | :wincmd w

" Word Processing mode
func! WordProcessorMode()
	setlocal textwidth=80
	setlocal smartindent
	setlocal spell spelllang=en_us
	setlocal noexpandtab
endfu
com! WP call WordProcessorMode()

" html autocompletion
autocmd Filetype html,xml,xsl source ~/.vim/autoload/closetag.vim
autocmd Filetype html,xml,xsl set omnifunc=htmlcomplete#CompleteTags
